version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./docker/file/Dockerfile
    command: bash -c "./docker/scripts/run.sh"
    env_file:
      - docker/env/.env.app
    container_name: tracker-http-app
    ports:
      - "9090:80"
    volumes:
      - ./:/tracker:delegated
    depends_on:
      - mysql
    links:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: tracker-database
    volumes:
      - ./docker/scripts/create_db_if_not_exists.sh:/docker-entrypoint-create_db_if_not_exists.sh:delegated
    ports:
      - "3308:3306"
    env_file:
      - docker/env/.env.database

  admin-notification:
    image: greenbone/exercise-admin-notification
    container_name: tracker-admin-notification
    ports:
      - "8080:8080"
